### ISSUE TITLE
Games that work with this wrapper?

### ISSUE THREAD

**Issue by alex9099** [roothorick/WineOpenVR#5]
Hi,

I was trying dreadhalls demo (the versions that are availible on their website) but the game just crashed :/
Are there any "100%" supported games?

**Comment by roothorick** [comment]
The vast majority of things use Direct3D. Due to how the video submit path works in OpenVR, Direct3D requires special logic in WineOpenVR that is not yet in a functional state, and work has been more or less stalled because I need to learn things about Vulkan that I've been having difficulty getting my head around. Pullreqs more than welcome.

In terms of what works and should work:

1. hellovr_opengl and hellovr_vulkan example programs from the OpenVR SDK have been tested and confirmed to work.
2. JanusVR *should* work. I suspect the "double vision" issue (#2) was a problem with early SteamVR, but haven't had the motivation to test.
3. In theory, Unity games will work if you pass -force-glcore. Has not been tested.
4. In theory, UE4 games will work if you pass -opengl3. In practice, most games are missing GLSL shaders and will fail to boot.
5. In theory, JOpenVR games using OpenGL (e.g. Spermination) *should* work. In practice, some kind of internal sanity check fails, hasn't been investigated further

You may want to subscribe to #1

**Comment by alex9099** [comment]
thanks, i'll test the examples

About Unity or UE (i think it was UE that dreadhalls used) it gives an error about cooked assets or something like that if i force opengl, maybe that problem with shaders that you were talking about :)

**Comment by roothorick** [comment]
If you read that message a little more closely you'll see the cooked assets thing is a hint to the developer as to the most likely cause of the issue (but not the cause here), and the real message is above that, which says pretty bluntly that it was unable to find a GLSL version of a requested shader in the game assets.
